
services:

  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: alice 
      POSTGRES_PASSWORD: alice 
      POSTGRES_DB: alice 
    volumes:
      - ./_data:/var/lib/postgresql/data
